// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoW3FJSGeSenGCa6MnvamZQFFQTefELd8',
    appId: '1:1027745859721:web:5599bae074c2eca2b75e58',
    messagingSenderId: '1027745859721',
    projectId: 'onlinerestaurant-e9af0',
    authDomain: 'onlinerestaurant-e9af0.firebaseapp.com',
    storageBucket: 'onlinerestaurant-e9af0.firebasestorage.app',
    measurementId: 'G-HYT0YZ6VB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr0cX_M583ExId5d4-qqWa7x95c217D04',
    appId: '1:1027745859721:android:a4ceb7008b0270dcb75e58',
    messagingSenderId: '1027745859721',
    projectId: 'onlinerestaurant-e9af0',
    storageBucket: 'onlinerestaurant-e9af0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1n4WqMvDdjMqCWLIwxBn7z-lr5hOaU-0',
    appId: '1:1027745859721:ios:d9a57eae4ded2b3cb75e58',
    messagingSenderId: '1027745859721',
    projectId: 'onlinerestaurant-e9af0',
    storageBucket: 'onlinerestaurant-e9af0.firebasestorage.app',
    iosBundleId: 'com.example.restaurant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1n4WqMvDdjMqCWLIwxBn7z-lr5hOaU-0',
    appId: '1:1027745859721:ios:d9a57eae4ded2b3cb75e58',
    messagingSenderId: '1027745859721',
    projectId: 'onlinerestaurant-e9af0',
    storageBucket: 'onlinerestaurant-e9af0.firebasestorage.app',
    iosBundleId: 'com.example.restaurant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoW3FJSGeSenGCa6MnvamZQFFQTefELd8',
    appId: '1:1027745859721:web:cb5027f45e4dacd9b75e58',
    messagingSenderId: '1027745859721',
    projectId: 'onlinerestaurant-e9af0',
    authDomain: 'onlinerestaurant-e9af0.firebaseapp.com',
    storageBucket: 'onlinerestaurant-e9af0.firebasestorage.app',
    measurementId: 'G-1KEENYSMTV',
  );
}
